# Generated by Django 4.2.16 on 2024-09-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessment_is_active_alter_assessment_user_id'),
        ('assessment', '0002_initial'),
    ]

    operations = [
    ]
