# Generated by Django 4.2.16 on 2024-09-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_assessment_assessment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='savings',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='spending_on_needs',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='spending_on_wants',
        ),
        migrations.AddField(
            model_name='assessment',
            name='answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='assessment',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assessment',
            name='question_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='question_text',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
