# Generated by Django 4.2.16 on 2024-09-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_id', models.CharField(max_length=255, unique=True)),
                ('criteria', models.TextField()),
                ('date_achieved', models.DateField()),
                ('description', models.TextField()),
                ('reward_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
