# Generated by Django 5.1.1 on 2024-09-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
