# Generated by Django 5.1.1 on 2024-09-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_achievement_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='achievement_id',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
