# Generated by Django 4.2.16 on 2024-09-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_id',
            new_name='id',
        ),
    ]
