# Generated by Django 4.2.16 on 2024-09-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_avatar_url_remove_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(choices=[('ShadowClaw', 'ShadowClaw'), ('Thunderwing', 'Thunderwing')], default='ShadowClaw', max_length=50),
        ),
    ]
