# Generated by Django 5.1.1 on 2024-09-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(choices=[('ShadowClaw', 'ShadowClaw'), ('Thunderwing', 'Thunderwing'), ('MysticFlare', 'MysticFlare'), ('AuroraBreath', 'AuroraBreath')], default='ShadowClaw', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
