# Generated by Django 5.1.1 on 2024-09-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar_alter_user_email'),
        ('users', '0005_alter_user_password'),
    ]

    operations = [
    ]
