# Generated by Django 5.1.1 on 2024-09-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessment_is_active_alter_assessment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
