# Generated by Django 4.2.16 on 2024-09-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_merge_20240911_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
