# Generated by Django 5.1.1 on 2024-09-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_assessment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='user_id',
        ),
    ]
