# Generated by Django 4.2.16 on 2024-09-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentSimulation',
            fields=[
                ('simulation_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_date', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(max_length=10)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
            ],
        ),
    ]
