# Generated by Django 4.2.16 on 2024-09-11 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_simulation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentsimulation',
            old_name='simulation_id',
            new_name='id',
        ),
    ]
