# Generated by Django 4.2.16 on 2024-09-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_simulation', '0002_rename_simulation_id_investmentsimulation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentsimulation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
