# Generated by Django 4.2.16 on 2024-09-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualmoney', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualmoney',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='virtualmoney',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
