# Generated by Django 5.1.1 on 2024-09-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualmoney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmoney',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
