# Generated by Django 5.1.1 on 2024-09-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualmoney', '0002_virtualmoney_is_active'),
        ('virtualmoney', '0003_virtualmoney_is_active'),
    ]

    operations = [
    ]
