name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r investika/requirements.txt

      - name: Set up Git remote for Heroku
        run: |
          git remote -v
          git remote add heroku https://git.heroku.com/investika.git || echo "Heroku remote already exists"

      - name: Set Heroku buildpack
        run: |
          heroku buildpacks:set heroku/python -a investika
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "investika"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
