name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  release:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: akhileshns/heroku-deploy@v3.13.15
         with:
           heroku_api_key: ${{ secrets.38f69816-f329-4f20-8ec6-665c5aee3eda }}
           heroku_app_name: "<Investika>"
           heroku_email: "<ndichujoyce8@gmail.com>"