name: Django CI/CD
on:
  push:
    branches:
      - main
      - staging
      - dev
  pull_request:
    branches:
      - main
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: List files
        run: ls -R
      - name: Install dependencies
        run: |
          pip install -r investika/requirements.txt
      - name: Run migrations
        run: |
          python manage.py migrate
      - name: Run tests
        run: |
          python manage.py test
          
      - name: formatting with Black
        id: action_black
        run: |
          black .
